# This is a basic workflow to help you get started with Actions

name: CI + CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Compile
        run: |
          echo Hello, Anthony!
      
  DeployDev:
    runs-on: ubuntu-latest
    name: Deploy to Dev
    needs: [Build]
    environment:
      name: Development
    steps:
      - name: Deploy
        uses: actions/checkout@v3
        run: |
          cd dev && ll
          echo ${{ secrets.ENVIRONMENT }} has been Deployed!
          
  DeployStg:
    runs-on: ubuntu-latest
    name: Deploy to Stg
    needs: [Build]
    environment:
      name: Staging
    steps:
      - name: Deploy
        run: |
          echo ${{ secrets.ENVIRONMENT }} has been Deployed!

  DeployProd:
    runs-on: ubuntu-latest
    name: Deploy to Prod
    needs: [DeployStg]
    environment:
      name: Production
    steps:
      - name: Deploy
        run: |
          echo ${{ secrets.ENVIRONMENT }} has been Deployed!
