# This is a basic workflow to help you get started with Actions

name: CI + CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DeployDev:
    runs-on: ubuntu-latest
    name: Deploy to Dev
    environment:
      name: Development
    steps:
      - name: Deploy
      - uses: actions/checkout@v3
      - run: |
          echo ${{ secrets.ENVIRONMENT }} has been Deployed!
          
  DeployStg:
    runs-on: ubuntu-latest
    name: Deploy to Stg
    needs: [DeployDev]
    environment:
      name: Staging
    steps:
      - name: Deploy
        run: |
          echo ${{ secrets.ENVIRONMENT }} has been Deployed!
  DeployProd:
    runs-on: ubuntu-latest
    name: Deploy to Prod
    needs: [DeployStg]
    environment:
      name: Production
    steps:
      - name: Deploy
        run: |
          echo ${{ secrets.ENVIRONMENT }} has been Deployed!